language: r
warnings_are_errors: true
sudo: false
cache: packages

r:
 - devel

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libblas-dev

r_packages:
  - Rcpp
  - RcppArmadillo
  - testthat
  - mgcv
  - devtools

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

script:
  - make install
  - make check
  - make test